ALTER SESSION SET CONTAINER = ESHOP_GLOBALE_PDB;

--db link to site 1
CREATE PUBLIC DATABASE LINK SITE_1
CONNECT TO globale_user IDENTIFIED BY globale_password
USING '//site1-db-s2:1521/ESHOP_SITE1_PDB';

--db link to site 2
CREATE PUBLIC DATABASE LINK SITE_2
CONNECT TO globale_user IDENTIFIED BY globale_password
USING '//site2-db-s2:1521/ESHOP_SITE2_PDB';
