ALTER SESSION SET CONTAINER = ESHOP_GLOBALE_PDB;
ALTER SESSION SET CURRENT_SCHEMA = globale_user;

CREATE OR REPLACE TRIGGER SYNC_INSERT_LIGNE 
AFTER INSERT ON LIGNES_COMMANDES
FOR EACH ROW
BEGIN
    IF :NEW.QUANTITE >= 100 THEN
        EXECUTE IMMEDIATE 'BEGIN INSERT_LIGNE@SITE_1(:1, :2, :3, :4, :5); END;'
        USING :NEW.ID_LIGNE_COMMANDE, :NEW.ID_COMMANDE, :NEW.ID_PRODUIT, :NEW.QUANTITE, :NEW.REMISE;
    ELSE
        EXECUTE IMMEDIATE 'BEGIN INSERT_LIGNE@SITE_2(:1, :2, :3, :4, :5); END;'
        USING :NEW.ID_LIGNE_COMMANDE, :NEW.ID_COMMANDE, :NEW.ID_PRODUIT, :NEW.QUANTITE, :NEW.REMISE;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SYNC_ERROR_INSERT: ' || SQLERRM);
        RAISE;
END SYNC_INSERT_LIGNE;
/
CREATE OR REPLACE TRIGGER SYNC_DELETE_LIGNE 
AFTER DELETE ON LIGNES_COMMANDES
FOR EACH ROW
BEGIN
    IF :OLD.QUANTITE >= 100 THEN
        EXECUTE IMMEDIATE 'BEGIN DELETE_LIGNE@SITE_1(:1); END;'
        USING :OLD.ID_LIGNE_COMMANDE;
    ELSE
        EXECUTE IMMEDIATE 'BEGIN DELETE_LIGNE@SITE_2(:1); END;'
        USING :OLD.ID_LIGNE_COMMANDE;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SYNC_ERROR_DELETE: ' || SQLERRM);
        RAISE;
END SYNC_DELETE_LIGNE;
/
CREATE OR REPLACE TRIGGER SYNC_UPDATE_LIGNE
AFTER UPDATE OF ID_PRODUIT, QUANTITE, REMISE ON LIGNES_COMMANDES
FOR EACH ROW
BEGIN
    IF :OLD.QUANTITE >= 100 THEN
        IF :NEW.QUANTITE >= 100 THEN
            EXECUTE IMMEDIATE 'BEGIN UPDATE_LIGNE@SITE_1(:1, :2, :3, :4); END;'
            USING :NEW.ID_LIGNE_COMMANDE, :NEW.ID_PRODUIT, :NEW.QUANTITE, :NEW.REMISE;
        ELSE
            -- bascule de site 1 vers site 2
            EXECUTE IMMEDIATE 'BEGIN DELETE_LIGNE@SITE_1(:1); END;'
            USING :OLD.ID_LIGNE_COMMANDE;
            EXECUTE IMMEDIATE 'BEGIN INSERT_LIGNE@SITE_2(:1, :2, :3, :4, :5); END;'
            USING :NEW.ID_LIGNE_COMMANDE, :NEW.ID_COMMANDE, :NEW.ID_PRODUIT, :NEW.QUANTITE, :NEW.REMISE;
        END IF;
    ELSE
        IF :NEW.QUANTITE < 100 THEN
            EXECUTE IMMEDIATE 'BEGIN UPDATE_LIGNE@SITE_2(:1, :2, :3, :4); END;'
            USING :NEW.ID_LIGNE_COMMANDE, :NEW.ID_PRODUIT, :NEW.QUANTITE, :NEW.REMISE;
        ELSE
            -- bascule de site 2 vers site 1
            EXECUTE IMMEDIATE 'BEGIN DELETE_LIGNE@SITE_2(:1); END;'
            USING :OLD.ID_LIGNE_COMMANDE;
            EXECUTE IMMEDIATE 'BEGIN INSERT_LIGNE@SITE_1(:1, :2, :3, :4, :5); END;'
            USING :NEW.ID_LIGNE_COMMANDE, :NEW.ID_COMMANDE, :NEW.ID_PRODUIT, :NEW.QUANTITE, :NEW.REMISE;
        END IF;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SYNC_UPDATE_ERROR: ' || SQLERRM);
        RAISE;
END SYNC_UPDATE_LIGNE;
/