SET SQLBLANKLINES ON;
SET SERVEROUTPUT ON;

ALTER SESSION SET CONTAINER = ESHOP_SITE2_PDB;
ALTER SESSION SET CURRENT_SCHEMA = globale_user;

CREATE TABLE FOURNISSEURS_2 (
    ID_FOURNISSEUR INTEGER,
    SOCIETE_FOURNISSEUR VARCHAR2(100 CHAR),
    CONTACT_FOURNISSEUR VARCHAR2(100 CHAR),
    FONCTION_FOURNISSEUR VARCHAR2(100 CHAR),
    ADRESSE_FOURNISSEUR VARCHAR2(100 CHAR),
    VILLE_FOURNISSEUR VARCHAR2(100 CHAR),
    REGION_FOURNISSEUR VARCHAR2(100 CHAR),
    CODE_POSTAL_FOURNISSEUR VARCHAR2(100 CHAR), -- NOT USED IN
    PAYS_FOURNISSEUR VARCHAR2(100 CHAR),
    TEL_FOURNISSEUR VARCHAR2(100 CHAR),
    FAX_FOURNISSEUR VARCHAR2(100 CHAR),-- NOT USED IN INSERT
    PRIMARY KEY (ID_FOURNISSEUR)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE FOURNISSEURS CREEE AVEC SUCCES');
END;
/

CREATE TABLE CATEGORIES_2 (
    ID_CATEGORIE INTEGER,
    NOM_CATEGORIE VARCHAR2(100 CHAR),
    DESCRIPTION CLOB,
    PRIMARY KEY (ID_CATEGORIE)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE CATEGORIES CREEE AVEC SUCCES');
END;
/

CREATE TABLE EMPLOYES_2 (
    ID_EMPLOYE INTEGER,
    NOM VARCHAR2(100 CHAR),
    PRENOM VARCHAR2(100 CHAR),
    FONCTION_EMPLOYE VARCHAR2(100 CHAR),
    TITRE_COURTOISIE VARCHAR2(100 CHAR),
    DATE_NAISSANCE DATE,
    DATE_EMBAUCHE DATE,
    ADRESSE_EMPLOYE VARCHAR2(100 CHAR),
    VILLE_EMPLOYE VARCHAR2(100 CHAR),
    PAYS_EMPLOYE VARCHAR2(100 CHAR),
    TEL_DOMICILE VARCHAR2(100 CHAR),
    PRIMARY KEY (ID_EMPLOYE)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE EMPLOYES CREEE AVEC SUCCES');
END;
/

CREATE TABLE CLIENTS_2 (
    ID_CLIENT NUMBER,
    CODE_CLIENT VARCHAR2(100),
    SOCIETE VARCHAR2(100) NOT NULL,
    CONTACT VARCHAR2(100) NOT NULL,
    FONCTION VARCHAR2(100) NOT NULL,
    ADRESSE VARCHAR2(100),
    VILLE VARCHAR2(100),
    DATE_NAISSANCE DATE,
    REGION VARCHAR2(100),
    CODE_POSTAL VARCHAR2(10),
    PAYS VARCHAR2(100),
    TELEPHONE VARCHAR2(100),
    FAX VARCHAR2(100),
    PRIMARY KEY (ID_CLIENT)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE CLIENTS CREEE AVEC SUCCES');
END;
/

CREATE TABLE PRODUITS_2 (
    ID_PRODUIT INTEGER,
    DESIGNATION VARCHAR2(100 CHAR),
    ID_FOURNISSEUR INTEGER,
    ID_CATEGORIE INTEGER,
    PRIX_UNITAIRE FLOAT,
    UNITES_EN_STOCK INTEGER,
    UNITES_COMMANDEES INTEGER,
    NIVEAU_REAPPROVISIONNEMENT INTEGER,
    INDISPONIBLE INTEGER CHECK (INDISPONIBLE IN (0, 1)),
    PRIMARY KEY (ID_PRODUIT),
    FOREIGN KEY (ID_FOURNISSEUR) REFERENCES FOURNISSEURS_2(ID_FOURNISSEUR),
    FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIES_2(ID_CATEGORIE)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE PRODUITS CREEE AVEC SUCCES');
END;
/

CREATE TABLE COMMANDES_2 (
    ID_COMMANDE INTEGER,
    ID_EMPLOYE INTEGER,
    ID_CLIENT NUMBER,
    DATE_COMMANDE DATE,
    DATE_LIVRAISON DATE,
    CHECK (DATE_LIVRAISON >= DATE_COMMANDE),
    ID_TRANSPORTEUR NUMBER(4, 0),
    FRAIS_PORT NUMBER(4, 0),
    PRIMARY KEY (ID_COMMANDE),
    FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYES_2(ID_EMPLOYE),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS_2(ID_CLIENT)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE COMMANDES CREEE AVEC SUCCES');
END;
/

CREATE TABLE LIGNES_COMMANDES_2 (
    ID_LIGNE_COMMANDE INTEGER,
    ID_COMMANDE INTEGER,
    ID_PRODUIT INTEGER,
    ID_CLIENT NUMBER,
    QUANTITE INTEGER,
    REMISE FLOAT,
    PRIMARY KEY (ID_LIGNE_COMMANDE),
    FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDES_2(ID_COMMANDE),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUITS_2(ID_PRODUIT),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS_2(ID_CLIENT)
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('TABLE LIGNES_COMMANDES CREEE AVEC SUCCES');
END;
/