SET SERVEROUTPUT ON SIZE UNLIMITED;
SET SQLBLANKLINES ON;

ALTER SESSION SET CONTAINER = ESHOP_SITE2_PDB;
ALTER SESSION SET CURRENT_SCHEMA = globale_user;

-- This script copies site 2 data from the globale PDB into the local _2 tables.
-- It waits for the globale DB to finish init (via INIT_COMPLETE marker table).
DECLARE
    v_ready INTEGER := 0;
BEGIN
    -- Wait for globale DB INIT_COMPLETE marker table
    FOR i IN 1..120 LOOP
        BEGIN
            EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INIT_COMPLETE@GLOBALE WHERE STATUS = ''READY''' INTO v_ready;
            EXIT;
        EXCEPTION
            WHEN OTHERS THEN
                v_ready := 0;
        END;
        DBMS_LOCK.SLEEP(5);
    END LOOP;

    IF v_ready = 0 THEN
        RETURN;
    END IF;

    -- 1) Fournisseurs supplying category 50 products
    INSERT INTO FOURNISSEURS_2 (ID_FOURNISSEUR, SOCIETE_FOURNISSEUR, CONTACT_FOURNISSEUR, FONCTION_FOURNISSEUR, ADRESSE_FOURNISSEUR, VILLE_FOURNISSEUR, REGION_FOURNISSEUR, CODE_POSTAL_FOURNISSEUR, PAYS_FOURNISSEUR, TEL_FOURNISSEUR, FAX_FOURNISSEUR)
    SELECT DISTINCT f.ID_FOURNISSEUR, f.SOCIETE_FOURNISSEUR, f.CONTACT_FOURNISSEUR, f.FONCTION_FOURNISSEUR, f.ADRESSE_FOURNISSEUR, f.VILLE_FOURNISSEUR, f.REGION_FOURNISSEUR, f.CODE_POSTAL_FOURNISSEUR, f.PAYS_FOURNISSEUR, f.TEL_FOURNISSEUR, f.FAX_FOURNISSEUR
    FROM FOURNISSEURS_G f
    WHERE f.ID_FOURNISSEUR IN (
        SELECT DISTINCT p.ID_FOURNISSEUR FROM PRODUITS_G p WHERE p.ID_CATEGORIE = 50
    )
    AND NOT EXISTS (SELECT 1 FROM FOURNISSEURS_2 lf WHERE lf.ID_FOURNISSEUR = f.ID_FOURNISSEUR);

    -- 2) Categories for site 2: only ID_CATEGORIE = 50
    INSERT INTO CATEGORIES_2 (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION)
    SELECT c.ID_CATEGORIE, c.NOM_CATEGORIE, c.DESCRIPTION
    FROM CATEGORIES_G c
    WHERE c.ID_CATEGORIE = 50
      AND NOT EXISTS (SELECT 1 FROM CATEGORIES_2 lc WHERE lc.ID_CATEGORIE = c.ID_CATEGORIE);

    -- 3) Employees referenced by qualifying commandes
    INSERT INTO EMPLOYES_2 (ID_EMPLOYE, NOM, PRENOM, FONCTION_EMPLOYE, TITRE_COURTOISIE, DATE_NAISSANCE, DATE_EMBAUCHE, ADRESSE_EMPLOYE, VILLE_EMPLOYE, PAYS_EMPLOYE, TEL_DOMICILE)
    SELECT DISTINCT e.ID_EMPLOYE, e.NOM, e.PRENOM, e.FONCTION_EMPLOYE, e.TITRE_COURTOISIE, e.DATE_NAISSANCE, e.DATE_EMBAUCHE, e.ADRESSE_EMPLOYE, e.VILLE_EMPLOYE, e.PAYS_EMPLOYE, e.TEL_DOMICILE
    FROM EMPLOYES_G e
    WHERE e.ID_EMPLOYE IN (
        SELECT c.ID_EMPLOYE FROM COMMANDES_G c WHERE c.ID_COMMANDE IN (
            SELECT lc.ID_COMMANDE FROM LIGNES_COMMANDES_G lc JOIN PRODUITS_G p ON lc.ID_PRODUIT = p.ID_PRODUIT WHERE lc.QUANTITE > 100 AND p.ID_CATEGORIE = 50
        )
    )
    AND NOT EXISTS (SELECT 1 FROM EMPLOYES_2 ee WHERE ee.ID_EMPLOYE = e.ID_EMPLOYE);

    -- 4) Clients referenced by qualifying commandes
    INSERT INTO CLIENTS_2 (ID_CLIENT, CODE_CLIENT, SOCIETE, CONTACT, FONCTION, ADRESSE, VILLE, DATE_NAISSANCE, REGION, CODE_POSTAL, PAYS, TELEPHONE, FAX)
    SELECT DISTINCT cl.ID_CLIENT, cl.CODE_CLIENT, cl.SOCIETE, cl.CONTACT, cl.FONCTION, cl.ADRESSE, cl.VILLE, cl.DATE_NAISSANCE, cl.REGION, cl.CODE_POSTAL, cl.PAYS, cl.TELEPHONE, cl.FAX
    FROM CLIENTS_G cl
    WHERE cl.ID_CLIENT IN (
        SELECT c.ID_CLIENT FROM COMMANDES_G c WHERE c.ID_COMMANDE IN (
            SELECT lc.ID_COMMANDE FROM LIGNES_COMMANDES_G lc JOIN PRODUITS_G p ON lc.ID_PRODUIT = p.ID_PRODUIT WHERE lc.QUANTITE > 100 AND p.ID_CATEGORIE = 50
        )
    )
    AND NOT EXISTS (SELECT 1 FROM CLIENTS_2 cc WHERE cc.ID_CLIENT = cl.ID_CLIENT);

    -- 5) Products in category 50
    INSERT INTO PRODUITS_2 (ID_PRODUIT, DESIGNATION, ID_FOURNISSEUR, ID_CATEGORIE, PRIX_UNITAIRE, UNITES_EN_STOCK, UNITES_COMMANDEES, NIVEAU_REAPPROVISIONNEMENT, INDISPONIBLE)
    SELECT p.ID_PRODUIT, p.DESIGNATION, p.ID_FOURNISSEUR, p.ID_CATEGORIE, p.PRIX_UNITAIRE, p.UNITES_EN_STOCK, p.UNITES_COMMANDEES, p.NIVEAU_REAPPROVISIONNEMENT, p.INDISPONIBLE
    FROM PRODUITS_G p
    WHERE p.ID_CATEGORIE = 50
      AND NOT EXISTS (SELECT 1 FROM PRODUITS_2 lp WHERE lp.ID_PRODUIT = p.ID_PRODUIT);

    -- 6) Commandes (needs EMPLOYES_2 and CLIENTS_2)
    INSERT INTO COMMANDES_2 (ID_COMMANDE, ID_EMPLOYE, ID_CLIENT, DATE_COMMANDE, DATE_LIVRAISON, ID_TRANSPORTEUR, FRAIS_PORT)
    SELECT DISTINCT c.ID_COMMANDE, c.ID_EMPLOYE, c.ID_CLIENT, c.DATE_COMMANDE, c.DATE_LIVRAISON, c.ID_TRANSPORTEUR, c.FRAIS_PORT
    FROM COMMANDES_G c
    WHERE c.ID_COMMANDE IN (
        SELECT lc.ID_COMMANDE FROM LIGNES_COMMANDES_G lc JOIN PRODUITS_G p ON lc.ID_PRODUIT = p.ID_PRODUIT WHERE lc.QUANTITE > 100 AND p.ID_CATEGORIE = 50
    )
    AND NOT EXISTS (SELECT 1 FROM COMMANDES_2 cm WHERE cm.ID_COMMANDE = c.ID_COMMANDE);

    -- 7) Lignes commandes (needs COMMANDES_2 and PRODUITS_2)
    INSERT INTO LIGNES_COMMANDES_2 (ID_LIGNE_COMMANDE, ID_COMMANDE, ID_PRODUIT, QUANTITE, REMISE)
    SELECT lc.ID_LIGNE_COMMANDE, lc.ID_COMMANDE, lc.ID_PRODUIT, lc.QUANTITE, lc.REMISE
    FROM LIGNES_COMMANDES_G lc
    JOIN PRODUITS_G p ON lc.ID_PRODUIT = p.ID_PRODUIT
    WHERE lc.QUANTITE > 100 AND p.ID_CATEGORIE = 50
      AND NOT EXISTS (SELECT 1 FROM LIGNES_COMMANDES_2 ll WHERE ll.ID_LIGNE_COMMANDE = lc.ID_LIGNE_COMMANDE);

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
/
