ALTER SESSION SET CONTAINER = ESHOP_GLOBALE_PDB;
ALTER SESSION SET CURRENT_SCHEMA = globale_user;
CREATE SEQUENCE CATEGORIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CLIENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMANDES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMPLOYES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FOURNISSEURS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LIGNES_COMMANDES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUITS_SEQ START WITH 1 INCREMENT BY 1;