SET FEEDBACK OFF;
SET DEFINE OFF;
ALTER SESSION SET CONTAINER = ESHOP_GLOBALE_PDB;
ALTER SESSION SET CURRENT_SCHEMA = globale_user;
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'dui','Donec,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'consequat','ut aliquam iaculis, lacus pede sagittis augue,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'at,','Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'metus.','venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'lacus','Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'id','Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'pellentesque,','et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'magna.','quam. Curabitur vel lectus. Cum sociis natoque penatibus');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ipsum','cursus et, magna. Praesent interdum');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'dignissim','blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'tempus','laoreet ipsum. Curabitur consequat,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Ut','ullamcorper viverra. Maecenas iaculis aliquet diam.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'lorem','elit, pretium et, rutrum');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'est.','at, egestas a, scelerisque');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'pede,','ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'convallis,','In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ac','est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'euismod','ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'dolor','ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'mi,','Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ut,','tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Lorem','semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'metus','Quisque');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'non','a, dui.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ornare','lectus, a sollicitudin');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'orci','vitae,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'mollis','non enim commodo hendrerit. Donec porttitor tellus');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'venenatis','nec tempus mauris erat eget');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ac','non quam. Pellentesque');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Aliquam','erat vitae risus. Duis a');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Suspendisse','bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'iaculis','ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'augue','lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'cursus','pede blandit congue. In scelerisque scelerisque dui.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'montes,','egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'enim.','libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'tempor','Morbi sit amet massa. Quisque porttitor eros');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'semper','diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'elementum','erat eget ipsum. Suspendisse sagittis. Nullam');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Nulla','et nunc. Quisque ornare tortor at risus. Nunc ac');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'lorem','et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'orci,','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'pede.','scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Fusce','diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'nec','pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'faucibus','at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'sit','tortor,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'consequat','auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'nec','volutpat. Nulla facilisis. Suspendisse');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Maecenas','aliquet diam. Sed diam lorem, auctor quis, tristique ac,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Proin','in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Sed','est mauris, rhoncus id, mollis');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'dolor.','lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'orci.','pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'laoreet,','risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'semper','amet');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'lorem,','vel, mauris. Integer sem elit, pharetra ut, pharetra sed,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'nibh','sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'sit','scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'pretium','porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'sit','magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ipsum.','arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Proin','Duis risus odio, auctor');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'egestas,','tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'mollis.','mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'pede','eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'posuere','nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'et,','lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'eros','Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'gravida.','fringilla purus mauris a nunc. In at pede. Cras vulputate velit');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'nulla','erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'iaculis','auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'In','Maecenas mi felis, adipiscing fringilla, porttitor vulputate,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'rhoncus.','sodales purus, in molestie tortor nibh sit amet orci.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'consectetuer','sit amet ornare lectus justo eu arcu. Morbi sit amet massa.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'et','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'rutrum','sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Vivamus','non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus.');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'interdum','vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Fusce','ut cursus luctus, ipsum leo');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'erat','erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Proin','Nam ac nulla. In tincidunt');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'nulla.','nec tellus. Nunc lectus pede,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Praesent','dictum eu,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'dolor.','amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'augue','amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Suspendisse','libero nec ligula consectetuer rhoncus. Nullam velit dui, semper');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Phasellus','hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'iaculis','massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Nullam','suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'non','dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'semper','Proin velit. Sed malesuada augue ut');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'nec,','ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'eu','dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'torquent','egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'ornare','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'rutrum,','turpis non enim. Mauris quis turpis vitae purus gravida');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Curabitur','penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'et,','malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor,');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Morbi','quis turpis vitae purus');
-- ============================================================
-- 2026 DATA (20% = 20 new rows)
-- ============================================================
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Smartphones','Mobile phones and accessories for 2026 lineup');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Laptops','Notebook computers and portable workstations');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Audio','Headphones, speakers and audio equipment');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Wearables','Smartwatches, fitness trackers and connected accessories');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Gaming','Video game consoles, controllers and accessories');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Home Automation','Smart home devices, hubs and connected sensors');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Photography','Digital cameras, lenses and photography gear');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Networking','Routers, switches and network infrastructure');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Storage','External drives, NAS and cloud storage devices');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Monitors','Computer displays and projection equipment');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Printers','Inkjet, laser and 3D printers');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Drones','Consumer and professional drone equipment');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'VR Equipment','Virtual reality headsets and motion controllers');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Tablets','Tablet computers and e-readers');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Peripherals','Keyboards, mice and input devices');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Power','Chargers, power banks and UPS systems');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Cables','HDMI, USB-C and specialty connectivity cables');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Software','Operating systems, productivity and security suites');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Servers','Rack servers, tower servers and components');
INSERT INTO CATEGORIES (ID_CATEGORIE, NOM_CATEGORIE, DESCRIPTION) VALUES (CATEGORIES_SEQ.NEXTVAL,'Electric Vehicles','EV accessories, chargers and smart car devices');
COMMIT;